Item 모델 추가
md2eoseo/se12-back pull request #2
Opened 2021-04-06 06:50 UTC by LimitofIntegral

Prisma 스키마에 Book을 나타내는 Item 모델을 추가했습니다.

2021-04-06 06:54 UTC, md2eoseo requested changes
문제점 몇 개 발견했어요

2021-04-06 06:54 UTC, md2eoseo commented on prisma/schema.prisma
> +  publicher String
publisher 오타났어요

2021-04-06 06:54 UTC, md2eoseo commented on prisma/schema.prisma
> +  price     String
price는 Int로 하는게 나중에 총 금액 계산할 때 좋을 것 같아요

2021-04-06 06:54 UTC, LimitofIntegral commented on prisma/schema.prisma
> +  publicher String
수정하겠습니다

2021-04-06 06:54 UTC, LimitofIntegral commented on prisma/schema.prisma
> +  price     String
Int로 수정할게요

2021-04-08 07:59 UTC, LimitofIntegral commented
getItem 구현하면서 title로 검색후 반환, author로 검색후 반환 등등 하려고 했는데, 특정 title 값 (ex "소프트웨어 공학") 의 activate값이 true인 것이 있는지 없는지만 ok의 true false로 반환이 됩니다...
해당 title값으로 db에서 해당하는 item의 필드를 다 긁어오고 싶었는데 아직 방법을 찾지를 못했어요.

2021-04-08 09:17 UTC, md2eoseo requested changes

2021-04-08 09:17 UTC, md2eoseo commented on items/createItem/createItem.typeDefs.js
> +      updatedAt: String!
createItem mutation type에 createdAt, updatedAt은 input으로 안 줘도 될거같아요

2021-04-08 09:17 UTC, md2eoseo commented on items/getItem/getItem.resolvers.js
> +import { introspectionFromSchema } from 'graphql';
사용하지 않는 패키지를 import 하는건 지우는게 좋을 것 같아요

2021-04-08 09:17 UTC, md2eoseo commented on items/createItem/createItem.resolvers.js
> +      return { ok: true };
만약을 위해 모든 resolvers에는 try catch 구문 쓰는게 좋을 거 같아요
users 브랜치에서 try catch 쓴 예시처럼 써주세용

2021-04-08 09:17 UTC, md2eoseo commented on items/getItem/getItem.resolvers.js
> +        const item = await client.item.findMany({
이 부분은 getItem 쿼리니까 findFirst로 바꿔서 하나만 찾을 수 있게 만드는게 좋을 것 같아요
findMany는 나중에 searchItems 쿼리 만들게 되면 그 때 쓰고요

2021-04-08 09:17 UTC, md2eoseo commented on items/getItem/getItem.resolvers.js
> +        if (item != '') {
여기서 item이 있는지 없는지 체크할 때는
`if (!item)` 으로 하는게 더 명확하고 에러가 생겼을 때 분명히 알 수 있을 것 같아요

2021-04-08 09:17 UTC, md2eoseo commented on items/getItem/getItem.resolvers.js
> +        if (item != '') {
여기도요

2021-04-08 09:21 UTC, md2eoseo requested changes

2021-04-08 09:21 UTC, md2eoseo commented on prisma/schema.prisma
> +  contents  String
필수가 아닌, null이 들어갈 수 있는 필드에는 뒤에 ? 붙여주세요
그리고 migrate 하면 됩니다.

2021-04-11 02:05 UTC, md2eoseo commented
src 폴더를 만들면서 구조가 좀 바뀌어서 items 폴더도 src 폴더로 옮겼습니다.

2021-04-11 02:05 UTC, md2eoseo approved these changes

2021-04-17 07:03 UTC, md2eoseo commented
Item과 관련된 Query, Mutation 작성했습니다.

2021-04-17 07:04 UTC, merged